@echo off
set LARCH_PATH=.;X:\splint-3.1.1\lib
set LCLIMPORTDIR=X:\splint-3.1.1\imports
set INCLUDE=C:\pspsdk\psp\include;C:\pspsdk\psp\sdk\include
set LINT=X:\splint-3.1.1\bin\splint.exe -unrecogcomments -exportlocal

%LINT% X:\workspace\minpspw\psp\pspsdk\src\audio\pspaudiolib.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\debug\callstack.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\debug\exception.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\debug\font.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\debug\gdb-kernellib.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\debug\gdb-stub.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\debug\gdb-userlib.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\debug\kprintf.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\debug\profiler.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\debug\pspdebugkb.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\debug\scr_printf.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\debug\sio.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\debug\stacktrace.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\debug\stdio.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\fpu\pspfpu.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\callbackFin.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\callbackSig.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\guInternal.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\resetValues.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuAlphaFunc.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuAmbient.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuAmbientColor.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuBeginObject.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuBlendFunc.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuBoneMatrix.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuBreak.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuCallList.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuCallMode.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuCheckList.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuClear.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuClearColor.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuClearDepth.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuClearStencil.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuClutLoad.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuClutMode.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuColor.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuColorFunc.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuColorMaterial.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuContinue.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuCopyImage.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuDepthBuffer.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuDepthFunc.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuDepthMask.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuDepthOffset.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuDepthRange.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuDisable.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuDispBuffer.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuDisplay.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuDrawArray.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuDrawArrayN.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuDrawBezier.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuDrawBuffer.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuDrawBufferList.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuDrawSpline.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuEnable.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuEndObject.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuFinish.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuFog.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuFrontFace.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuGetAllStatus.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuGetMemory.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuGetStatus.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuInit.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuLight.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuLightAtt.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuLightColor.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuLightMode.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuLightSpot.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuLogicalOp.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuMaterial.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuModelColor.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuMorphWeight.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuOffset.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuPatchDivide.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuPatchFrontFace.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuPatchPrim.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuPixelMask.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuScissor.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuSendCommandf.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuSendCommandi.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuSendList.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuSetAllStatus.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuSetCallback.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuSetDither.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuSetMatrix.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuSetStatus.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuShadeModel.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuSignal.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuSpecular.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuStart.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuStencilFunc.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuStencilOp.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuSwapBuffers.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuSync.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuTerm.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuTexEnvColor.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuTexFilter.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuTexFlush.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuTexFunc.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuTexImage.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuTexLevelMode.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuTexMapMode.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuTexMode.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuTexOffset.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuTexProjMapMode.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuTexScale.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuTexSlope.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuTexSync.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuTexWrap.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sceGuViewport.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gu\sendCommand.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gum\gumInternal.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gum\pspgum.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\gum\pspgum_vfpu.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\libc\alloc.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\libc\init.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\libc\libcglue.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\libc\qsort.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\libc\stdio.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\libc\stdlib.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\libc\string.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\libc\terminate.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\libc\xprintf.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\prof\prof.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\sdk\fixup.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\sdk\inethelper.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\sdk\loadmodule.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\sdk\modulemgr_patches.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\sdk\query_mod.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\sdk\threadutils.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\startup\crt0.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\startup\crt0_prx.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\startup\dummy.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\startup\prxexports.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\user\pspintrman.c
%LINT% X:\workspace\minpspw\psp\pspsdk\src\vfpu\pspvfpu.c
