#!/bin/sh

prefix=$(psp-config --psp-prefix)
exec_prefix=${prefix}
exec_prefix_set=no

usage="\
Usage: sdl-config [--prefix[=DIR]] [--exec-prefix[=DIR]] [--version] [--cflags] [--libs] [--static-libs]"

if test $# -eq 0; then
      echo "${usage}" 1>&2
      exit 1
fi

while test $# -gt 0; do
  case "$1" in
  -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
  *) optarg= ;;
  esac

  case $1 in
    --prefix=*)
      prefix=$optarg
      if test $exec_prefix_set = no ; then
        exec_prefix=$optarg
      fi
      ;;
    --prefix)
      echo $prefix
      ;;
    --exec-prefix=*)
      exec_prefix=$optarg
      exec_prefix_set=yes
      ;;
    --exec-prefix)
      echo $exec_prefix
      ;;
    --version)
      echo 1.2.9
      ;;
    --cflags)
      echo -I${prefix}/include/SDL  -Dmain=SDL_main

      # The portable way of including SDL is #include "SDL.h"
      #if test ${prefix}/include != /usr/include ; then
      #    # Handle oddities in Win32 path handling (assumes prefix)
      #    prefix=`echo ${prefix} | sed 's,^//\([A-Z]\),\1:,'`
      #
      #    includes=-I${prefix}/include
      #fi
      #echo $includes -I${prefix}/include/SDL  -Dmain=SDL_main
      ;;
#    --libs)
#      libdirs="-L${exec_prefix}/lib "
#      echo $libdirs -lSDLmain -lSDL 
#      ;;
#    --static-libs)
    --libs|--static-libs)
      libdirs="-L${exec_prefix}/lib "
      echo $libdirs -lSDLmain -lSDL  -lm -lGL -lpspvfpu -L$(psp-config --pspsdk-path)/lib -lpspdebug -lpspgu -lpspctrl -lpspge -lpspdisplay -lpsphprm -lpspsdk -lpsprtc -lpspaudio -lc -lpspuser -lpsputility -lpspkernel -lpspnet_inet
      ;;
    *)
      echo "${usage}" 1>&2
      exit 1
      ;;
  esac
  shift
done
